version: "2"
services:

  api:
    image: ddk_core_build
    container_name: ddknode-api
    volumes:
      - ../data/DDKCORE:/home/ddk
      - /home/ddk/logs
    networks:
      ddk-testnet:
        ipv4_address: 10.5.0.6
    env_file:
      - ddkcoin.env
    environment:
      - SERVICE=API
      - MODE=WATCH
      - PROFILING=false
    ports:
    - "7008:7008"
    restart: always

  ddk:
    image: ddk_core_build
    container_name: ddknode-core
    volumes:
      - ../data/DDKCORE:/home/ddk
      - /home/ddk/logs
    networks:
      ddk-testnet:
        ipv4_address: 10.5.0.5
    env_file:
      - ddkcoin.env
    environment:
      - SERVICE=CORE
      - MODE=WATCH
      - PROFILING=false
      - MODE=DEBUG
    ports:
      - "9229:9229"
      - "7007:7007"
      - "7009:7009"
    restart: always

  db:
     image: postgres:9.6-alpine
     container_name: ddknode-db
     volumes:
       - db-data:/var/lib/postgresql/data
     networks:
       ddk-testnet:
         ipv4_address: 10.5.0.4

     environment:
       - POSTGRES_USER=lisk
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=ddk
     restart: always

networks:
  ddk-testnet:
    external:
      name: docker_ddk-testnet

volumes:
  db-data:
