version: "2"
services:

  ddk:
    image: ddk_core_build
    container_name: ddknode-core
    networks:
      ddk-testnet:
        ipv4_address: 10.5.0.5

    env_file:
      - ddkcoin.env
    ports:
      - "7007:7007"
      - "8080:8080"
    restart: always

  db:
    image: postgres:9.6-alpine
    container_name: ddknode-db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      ddk-testnet:
        ipv4_address: 10.5.0.4

    environment:
      - POSTGRES_USER=lisk
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ddk
    restart: always

  redis:
    image: redis:alpine
    container_name: ddknode-redis
    volumes:
      - redis-data:/data
    networks:
      ddk-testnet:
        ipv4_address: 10.5.0.3
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: ddknode-elasticsearch

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      ddk-testnet:
        ipv4_address: 10.5.0.2
    restart: always

  nginx:
    build:
      context: ../data/DDKUI
      dockerfile: nginx.Dockerfile
    container_name: ddknode-nginx
    networks:
      ddk-testnet:
        ipv4_address: 10.5.0.7
    volumes:
      - ../data/DDKUI/certs/:/etc/nginx/live/ddkthailand01.ddkoin.com/
      - ./ddk.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ddkcoin.env

networks:
  ddk-testnet:
    external:
      name: docker_ddk-testnet


volumes:
  db-data:
  ddk-logs:
  redis-data:
  es-data:
    driver: local
