version: "2"
services:

  ddk:
    image: ddk_core_build
    container_name: ddknode-core-2
    networks:
      ddk-testnet:
        ipv4_address: 10.7.0.5
    volumes:
      - ../data/DDKCORE:/home/ddk
      - /home/ddk/logs
    env_file:
      - ddkcoin.env
    environment:
    - SERVICE=CORE
    - PROFILING=false
    restart: always

  db:
     image: postgres:9.6-alpine
     container_name: ddknode-db-2
     volumes:
       - db-data:/var/lib/postgresql/data
     networks:
       ddk-testnet:
         ipv4_address: 10.7.0.4

     environment:
       - POSTGRES_USER=lisk
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=ddk
     restart: always

networks:
  ddk-testnet:
    external:
      name: docker_ddk-testnet


volumes:
  db-data:
