version: "2"
services:

  ddk:
    image: "${REGISTRY_URL}/ddk/core"
    container_name: ddknode-core-2
    networks:
      ddk-testnet:
        ipv4_address: 10.7.0.5

    env_file:
      - ddkcoin.env
    restart: always

  ddkui:
    image: "${REGISTRY_URL}/ddk/ui"
    container_name: ddknode-ui-2
    networks:
      ddk-testnet:
        ipv4_address: 10.7.0.6

    environment:
      - PORT=7000
    restart: always

  db:
    build:
      context: ../data
      dockerfile: Dockerfile.PGDB
    container_name: ddknode-db-2
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      ddk-testnet:
        ipv4_address: 10.7.0.4
        
    env_file:
      - ddkcoin.env
    restart: always

  redis:
    image: redis:alpine
    container_name: ddknode-redis-2
    volumes:
      - redis-data:/data
    networks:
      ddk-testnet:
        ipv4_address: 10.7.0.3
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: ddknode-elasticsearch-2

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=$ES_JAVA_OPTS
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    networks:
      ddk-testnet:
        ipv4_address: 10.7.0.2
    restart: always


networks:
  ddk-testnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
         gateway: 10.7.0.1


volumes:
  db-data:
  ddk-logs:
  redis-data:
  es-data:
    driver: local
