FROM node:8.9.1

RUN adduser ddk --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password

RUN npm install --global grunt-cli@latest

RUN npm install --global bower@latest

USER ddk

WORKDIR /home/ddk

COPY DDK-UI/package.json /home/ddk

RUN mkdir -p /home/ddk/public

COPY DDK-UI/public/package.json /home/ddk/public

COPY DDK-UI/public/bower.json /home/ddk/public

RUN npm install && \
    cd public && \
    bower install && \
    npm install
    
COPY --chown=ddk DDK-UI /home/ddk

RUN cd public && grunt release

CMD ["npm", "start"]