version: "2"
services:

  ddk:
    build:
      context: ../data
      dockerfile: Dockerfile.CORE
    container_name: ddknode-core-1
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.5

    env_file:
      - ddkcoin.env
    restart: always

  ddkui:
    build:
      context: ../data
      dockerfile: Dockerfile.UI
    container_name: ddknode-ui-1
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.6

    environment:
      - PORT=7000
    restart: always

  db:
    build:
      context: ../data
      dockerfile: Dockerfile.PGDB
    container_name: ddknode-db-1
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.4
        
    env_file:
      - ddkdb.env
    restart: always

  redis:
    image: redis:alpine
    container_name: ddknode-redis-1
    volumes:
      - redis-data:/data
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.3
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: ddknode-elasticsearch-1

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.2
    restart: always


networks:
  ddk-testnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1


volumes:
  db-data:
  ddk-logs:
  redis-data:
  es-data:
    driver: local
