version: "2"
services:

  watch:
    image: ddk_core_build
    container_name: ddk-watch-server
    volumes:
      - ../data/DDKCORE:/home/ddk
      - /home/ddk/logs
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.8
    env_file:
      - ddkcoin.env
    environment:
      - SERVICE=WATCH

  ddk:
    build:
      context: ../data/DDKCORE
      dockerfile: dev.Dockerfile
    image: ddk_core_build
    container_name: ddknode-core-1
    volumes:
      - ../data/DDKCORE:/home/ddk
      - /home/ddk/logs
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.5
    env_file:
      - ddkcoin.env
    environment:
      - SERVICE=CORE
      - MODE=WATCH
      - PROFILING=false
    restart: always

  db:
    image: postgres:9.6-alpine
    container_name: ddknode-db-1
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      ddk-testnet:
        ipv4_address: 10.6.0.4
    environment:
      - POSTGRES_USER=lisk
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ddk
    restart: always

networks:
  ddk-testnet:
    external:
      name: docker_ddk-testnet

volumes:
  db-data:
